config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'



  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/cart',    to: 'carts#show'
  post   '/cart',    to: 'carts#create'

  resources :users
  resources :products
  resources :reviews,  only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :users, through: :review
  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :carts

  validates :name,
            presence: true,
            length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

  validates :price,
            presence: true

  validates :description,
            presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def index
    @products = Product.paginate(page: params[:page], :per_page => 5)
  end
  def show
    @product = Product.find(params[:id])
    @review = @product.reviews.build
    @feed_items = @product.reviews.paginate(page: params[:page], :per_page => 10)
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product deleted"
    redirect_to products_url
  end

def new
  @product = Product.new
end

def create
  @product = Product.new(product_params)
  if @product.save
    flash[:success] = 'Product successfully added!'
    redirect_to @product
  else
    redirect_to :back
  end
end

def edit
  @product = Product.find(params[:id])
  end

def update
  @product = Product.find(params[:id])
  if @product.update_attributes(product_params)
    flash[:success] = "Product updated Successfully"
    redirect_to @product
  else
    redirect_to :back
  end
  end

private

def product_params
  params.require(:product).permit(:picture, :name, :price, :description)
end

end

app/views/products/_product.html.erb
<li>
  <%= link_to product do %>
  <div class="row">
     <div class="col-md-5">
     <img src="<%= product.picture %>"/>
     <div class="col-md-8">
     <%= product.name %><br>
     <p>Price : <%= product.price %></p>
   </div>
 </div>
 </div>
  <% end %>

<% if current_user && current_user.admin? && logged_in? %>
        <p class="admin-option"> <%= link_to "show", product %> | <%= link_to "edit", edit_product_path(product.id) %> | <%= link_to "delete", product, method: :delete,
                                 data: { confirm: "You sure?" } %>
                               </p>

 <% end %>
</li>

app/views/products/edit.html.erb
<% provide(:title, 'Edit Product') %>
<% provide(:ptitle, 'Edit Product') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/products/index.html.erb
<% provide(:title, 'All Products') %>
<% provide(:ptitle, 'All Products') %>


<%= will_paginate %>

<ul class="products">

      <%= render @products %>

</ul>

<%= will_paginate %>

app/views/products/new.html.erb
<% provide(:title, 'Add Product') %>
<% provide(:ptitle, 'Add Product') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "Add Product", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>

<div class="row">
    <aside class="col-md-4">
        <img src="<%= @product.picture %>"/>

    </aside>

    <div class="col-md-8">
        <h3>
            <%= @product.name.titleize %>
        </h3>
        <div class="product-attr">
            <p>Description:</p>
            <%= @product.description %>
            <p>Price:</p>
            <%= @product.price %>
            <p>
                <%= link_to "Add to Cart", cart_path(product_id: @product.id), method: :post %>

                <% if current_user.admin? %>

              | <%= link_to "Edit", edit_product_path(@product.id) %> | <%= link_to "Delete Product", @product, method: :delete,
                                   data: { confirm: "You sure?" } %>
               <% end %>
            </p>
              <h4>Reviews</h4>
            <%= render 'shared/feed' %>
            <section class="review_form">
                <%= render 'shared/review_form' %>
            </section>
        </div>
    </div>



</div>